apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: catalunsha
spec:
  hostname: catalunsha
  exitNode: true
  proxyClass: catalunsha
  subnetRouter:
    advertiseRoutes:
      - "10.0.0.0/8"
