apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web
  namespace: nginx-fabric
spec:
  secretName: web
  issuerRef:
    name: letsencrypt-short-lived-prod
    kind: ClusterIssuer
  dnsNames:
    - nahue.ar
    - www.nahue.ar
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  usages:
    - server auth
  isCA: false
