apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  # replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: data
          nfs:
            path: "/mnt/NAS-T/k8s-volumes/ephemeral/archmirror/data"
            server: 10.10.20.10
      containers:
        - name: web
          image: npastorale/web:0.0.1@sha256:05b492cc9a3d8043bd3b0ce3c8b5fbb18836de3d79429e84ceb1e9a756a2823a
          resources:
            requests:
              memory: "56Mi"
              cpu: "100m"
            limits:
              memory: "8Gi"
              cpu: "4"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
