apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tautulli
  labels:
    app: tautulli
spec:
  serviceName: tautulli
  replicas: 1
  selector:
    matchLabels:
      app: tautulli
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      volumes:
        - name: config
          nfs:
            path: "/mnt/NAS-T/k8s-volumes/persistent/tautulli/config"
            server: 10.10.20.10
      containers:
        - name: tautulli
          image: lscr.io/linuxserver/tautulli:v2.17.1-ls229@sha256:7077fd6654547c225ca5a740c4c954379129589f875c84cbe138641d4dd8a9d9
          resources:
            requests:
              memory: "56Mi"
              cpu: "100m"
            limits:
              memory: "8Gi"
              cpu: "4"
          env:
            - name: TZ
              value: "Europe/Madrid"
            - name: PUID
              value: "1000"
            - name: GUID
              value: "1000"
          readinessProbe:
            tcpSocket:
              port: 8181
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 8181
              name: web
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: false
