apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: npastorale@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    profile: classic
    solvers:
      - dns01:
          rfc2136:
            nameserver: 10.10.20.50
            tsigKeyName: ddns-key
            tsigAlgorithm: HMACSHA512
            tsigSecretSecretRef:
              name: ddns-key
              key: ddns-key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-classic-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: npastorale@gmail.com
    privateKeySecretRef:
      name: letsencrypt-classic-prod
    profile: classic
    solvers:
      - dns01:
          rfc2136:
            nameserver: 10.10.20.50
            tsigKeyName: ddns-key
            tsigAlgorithm: HMACSHA512
            tsigSecretSecretRef:
              name: ddns-key
              key: ddns-key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-short-lived-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: your-email@example.com
    privateKeySecretRef:
      name: letsencrypt-short-lived-staging
    profile: shortlived
    solvers:
      - dns01:
          rfc2136:
            nameserver: 10.10.20.50
            tsigKeyName: ddns-key
            tsigAlgorithm: HMACSHA512
            tsigSecretSecretRef:
              name: ddns-key
              key: ddns-key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-short-lived-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: npastorale@gmail.com
    privateKeySecretRef:
      name: letsencrypt-short-lived-prod
    profile: shortlived
    solvers:
      - dns01:
          rfc2136:
            nameserver: 10.10.20.50
            tsigKeyName: ddns-key
            tsigAlgorithm: HMACSHA512
            tsigSecretSecretRef:
              name: ddns-key
              key: ddns-key
