apiVersion: batch/v1
kind: CronJob
metadata:
  name: bind-kubectl
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 4
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: bind-external-updater
              configMap:
                name: bind-external-updater
            - name: data
              nfs:
                path: "/mnt/NAS-T/k8s-volumes/persistent/bind/external/data"
                server: 10.10.20.10
            - name: zone-update
              configMap:
                name: zone-update
                defaultMode: 0755
          serviceAccountName: bind-kubectl
          containers:
            - name: bind-kubectl
              image: ghcr.io/npastorale/kubectl:1.36.1-r0@sha256:aaa3e0f13579c237364ddf3c4ebe865a26ca7d5e75f83917b32675a6da34804e
              command: ["/main.bash"]
              volumeMounts:
                - name: data
                  mountPath: /etc/bind/master
                  readOnly: false
                - name: zone-update
                  mountPath: /main.bash
                  subPath: main.bash
          restartPolicy: OnFailure
