apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esphome
  labels:
    app: esphome
spec:
  serviceName: esphome
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: esphome
  template:
    metadata:
      labels:
        app: esphome
    spec:
      volumes:
        - name: config
          nfs:
            path: "/mnt/NAS-T/k8s-volumes/persistent/esphome/config"
            server: 10.10.20.10
      hostNetwork: true
      containers:
        - name: esphome
          image: ghcr.io/esphome/esphome:2026.6.2@sha256:526a75c8d64a0d962a3b088c3af4fa7cf8ecf7161b995be57fc95b0726496a39
          resources:
            requests:
              memory: "56Mi"
              cpu: "100m"
            limits:
              memory: "8Gi"
              cpu: "4"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Madrid"
          ports:
            - containerPort: 6052
          volumeMounts:
            - name: config
              mountPath: /config
