apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esphome
  labels:
    app: esphome
spec:
  serviceName: esphome
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: esphome
  template:
    metadata:
      labels:
        app: esphome
    spec:
      volumes:
        - name: config
          nfs:
            path: "/mnt/NAS-T/k8s-volumes/persistent/esphome/config"
            server: 10.10.20.10
      hostNetwork: true
      containers:
        - name: esphome
          image: ghcr.io/esphome/esphome:2026.5.2@sha256:d2c415e4b44bd858d18ea09c4e9db6f03f2367a769cd07f92e7c6f7ff52a7ee8
          resources:
            requests:
              memory: "56Mi"
              cpu: "100m"
            limits:
              memory: "8Gi"
              cpu: "4"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Madrid"
          ports:
            - containerPort: 6052
          volumeMounts:
            - name: config
              mountPath: /config
