apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ghcr-auth
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: oci
        url: oci://ghcr.io
        username: "{{ .username }}"
        password: "{{ .token }}"
  data:
    - secretKey: username
      remoteRef:
        key: ghcr
        property: username
    - secretKey: token
      remoteRef:
        key: ghcr
        property: token
