apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: object-storage
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: object-storage
    creationPolicy: Owner
    template:
      data:
        connection: |
          provider: AWS
          region: garage
          aws_access_key_id: {{ .accessKeyId }}
          aws_secret_access_key: {{ .secretAccessKey }}
          aws_signature_version: 4
          host: {{ .host }}
          endpoint: '{{ .endpoint }}'
          path_style: true
  data:
    - secretKey: accessKeyId
      remoteRef:
        key: gitlab/garage
        property: access_key_id
    - secretKey: secretAccessKey
      remoteRef:
        key: gitlab/garage
        property: secret_access_key
    - secretKey: host
      remoteRef:
        key: gitlab/garage
        property: host
    - secretKey: endpoint
      remoteRef:
        key: gitlab/garage
        property: endpoint
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pages-storage
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pages-storage
    creationPolicy: Owner
    template:
      data:
        connection: |
          provider: AWS
          region: garage
          aws_access_key_id: {{ .accessKeyId }}
          aws_secret_access_key: {{ .secretAccessKey }}
          aws_signature_version: 4
          host: {{ .host }}
          endpoint: '{{ .endpoint }}'
          path_style: true
  data:
    - secretKey: accessKeyId
      remoteRef:
        key: gitlab/garage
        property: access_key_id
    - secretKey: secretAccessKey
      remoteRef:
        key: gitlab/garage
        property: secret_access_key
    - secretKey: host
      remoteRef:
        key: gitlab/garage
        property: host
    - secretKey: endpoint
      remoteRef:
        key: gitlab/garage
        property: endpoint
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backup-storage
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: backup-storage
    creationPolicy: Owner
    template:
      data:
        config: |
          [default]
          access_key = {{ .accessKeyId }}
          secret_key = {{ .secretAccessKey }}
          host_base = {{ .hostBase }}
          host_bucket = {{ .hostBase }}
          use_https = False
          signature_v2 = False
  data:
    - secretKey: accessKeyId
      remoteRef:
        key: gitlab/garage
        property: access_key_id
    - secretKey: secretAccessKey
      remoteRef:
        key: gitlab/garage
        property: secret_access_key
    - secretKey: hostBase
      remoteRef:
        key: gitlab/garage
        property: host_base
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-storage
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: registry-storage
    creationPolicy: Owner
    template:
      data:
        config: |
          s3:
            accesskey: {{ .accessKeyId }}
            secretkey: {{ .secretAccessKey }}
            region: garage
            regionendpoint: {{ .endpoint }}
            bucket: registry
            forcepathstyle: true
            v4auth: true
  data:
    - secretKey: accessKeyId
      remoteRef:
        key: gitlab/garage
        property: access_key_id
    - secretKey: secretAccessKey
      remoteRef:
        key: gitlab/garage
        property: secret_access_key
    - secretKey: endpoint
      remoteRef:
        key: gitlab/garage
        property: endpoint
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-runner-cache-s3
  namespace: gitlab
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: gitlab-runner-cache-s3
    creationPolicy: Owner
  data:
    - secretKey: accesskey
      remoteRef:
        key: gitlab/garage
        property: access_key_id
    - secretKey: secretkey
      remoteRef:
        key: gitlab/garage
        property: secret_access_key
