apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: hindsight
  namespace: hindsight
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie@sha256:37ade18dbdddba430858c72725aceeec66f33fa5333e82ea1df4942f6c1c83a3
  storage:
    size: 10Gi
    storageClass: truenas-nvmeof
  bootstrap:
    initdb:
      database: hindsight
      owner: hindsight
      secret:
        name: hindsight-db
  postgresql:
    shared_preload_libraries:
      - vector
    extensions:
      - name: pgvector
        image:
          reference: ghcr.io/cloudnative-pg/pgvector:0.8.6-202610011123-18-trixie@sha256:af88b0b09f85683cc981407bc53546ea410242fa0455fa2f2cd8d1dc56833413
