apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: hindsight
  namespace: hindsight
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie@sha256:37ade18dbdddba430858c72725aceeec66f33fa5333e82ea1df4942f6c1c83a3
  storage:
    size: 10Gi
    storageClass: truenas-nvmeof
  bootstrap:
    initdb:
      database: hindsight
      owner: hindsight
      secret:
        name: hindsight-db
  postgresql:
    shared_preload_libraries:
      - vector
    extensions:
      - name: pgvector
        image:
          reference: ghcr.io/cloudnative-pg/pgvector:0.8.7-202610071437-18-trixie@sha256:41d3480fdb7b57bd90f4ba7a38f50766d4c05fd64c69bcd99f87c5bd12e753a1
