apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hindsight-codex-auth
spec:
  storageClassName: nfs-csi-persistent
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
