apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: audiobookshelf
spec:
  secretName: audiobookshelf-tls
  issuerRef:
    name: letsencrypt-short-lived-prod
    kind: ClusterIssuer
  dnsNames:
    - audiobookshelf.nahue.ar
