apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: audiobookshelf
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: audiobookshelf-https
  body:
    maxSize: "5g"
