apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: jellyfin
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: jellyfin-https
  body:
    maxSize: "100m"
