# apiVersion: postgresql.cnpg.io/v1
# kind: Cluster
# metadata:
#   name: postgres-18
# spec:
#   instances: 1
#   imageName: ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie@sha256:37ade18dbdddba430858c72725aceeec66f33fa5333e82ea1df4942f6c1c83a3
#   storage:
#     size: 10Gi
#     storageClass: nfs-csi-persistent
# ---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-gitlab
  namespace: gitlab
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie@sha256:37ade18dbdddba430858c72725aceeec66f33fa5333e82ea1df4942f6c1c83a3
  storage:
    size: 50Gi
    storageClass: truenas-nvmeof
