apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web
  namespace: nginx-fabric
spec:
  secretName: web
  issuerRef:
    name: letsencrypt-short-lived-staging
    kind: ClusterIssuer
  dnsNames:
    - mirrors.nahue.ar
