apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: archmirror-web
spec:
  secretName: archmirror-web
  issuerRef:
    name: letsencrypt-short-lived-staging
    kind: ClusterIssuer
  dnsNames:
    - mirrors.nahue.ar
