apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: archmirror-https
spec:
  hostnames:
    - mirrors.nahue.ar
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external-nginx
      namespace: nginx-fabric
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: http-server
          port: 80
          weight: 1
