apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: hindsight
spec:
  name: hindsight
  owner: hindsight
  cluster:
    name: hindsight
  extensions:
    - name: vector
      ensure: present
