apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lidarr
  labels:
    app: lidarr
spec:
  serviceName: lidarr
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      volumes:
        - name: config
          nfs:
            path: "/mnt/NAS-T/k8s-volumes/persistent/lidarr/config"
            server: 10.10.20.10
        - name: persistent-data
          nfs:
            path: "/mnt/NAS-T/k8s-volumes/persistent/plex/data"
            server: 10.10.20.10
      containers:
        - name: lidarr
          image: lscr.io/linuxserver/lidarr:3.1.0.4875-ls39@sha256:2e4cdc7c8d5fa36915f446a29976ee01d3f9cc9722b8530a09121c76fbabef55
          resources:
            requests:
              memory: "56Mi"
              cpu: "100m"
            limits:
              memory: "8Gi"
              cpu: "4"
          env:
            - name: TZ
              value: "Europe/Madrid"
            - name: PUID
              value: "1000"
            - name: GUID
              value: "1000"
          readinessProbe:
            httpGet:
              port: 8686
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 8686
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3
          ports:
            - containerPort: 8686
              name: web
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: false
            - name: persistent-data
              mountPath: /persistent-data
              readOnly: false
