apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-cd
    helm:
      valuesObject:
        global:
          domain: argocd.nahue.ar
          revisionHistoryLimit: 0
        controller:
          revisionHistoryLimit: 0
        dex:
          enabled: false
        configs:
          params:
            server.insecure: true
        server:
          service:
            servicePortHttp2: 8080
            servicePortHttp2AppProtocol: kubernetes.io/h2c
          listenerset:
            enabled: true
            parentRef:
              name: internal
              namespace: nginx-fabric
          httproute:
            enabled: true
          # grpcroute:
          #   enabled: true
          certificate:
            enabled: true
            issuer:
              group: "cert-manager.io"
              kind: "ClusterIssuer"
              name: "letsencrypt-short-lived-prod"
            privateKey:
              algorithm: ECDSA
              encoding: PKCS8
              size: 384
              rotationPolicy: Always
            usages:
              - server auth
        extraObjects:
          # ------------------------------------------------------------
          # External webhook
          # ------------------------------------------------------------
          - apiVersion: gateway.networking.k8s.io/v1
            kind: ListenerSet
            metadata:
              name: argocd-server-webhook
            spec:
              parentRef:
                name: external
                namespace: nginx-fabric
              listeners:
                - name: https
                  port: 443
                  protocol: HTTPS
                  hostname: argocd.nahue.ar
                  tls:
                    mode: Terminate
                    certificateRefs:
                      - group: ""
                        kind: Secret
                        name: argocd-server-tls
                  allowedRoutes:
                    namespaces:
                      from: Same
          - apiVersion: gateway.networking.k8s.io/v1
            kind: HTTPRoute
            metadata:
              name: argocd-server-webhook
              annotations:
                external-dns.alpha.kubernetes.io/exclude: "true"
            spec:
              parentRefs:
                - group: gateway.networking.k8s.io
                  kind: ListenerSet
                  name: argocd-server-webhook
                  sectionName: https
              hostnames:
                - argocd.nahue.ar
              rules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /api/webhook
                  backendRefs:
                    - group: ""
                      kind: Service
                      name: argocd-server
                      port: 80
                      weight: 1
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 10.9.2
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
