apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitlab
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gitlab
    repoURL: https://charts.gitlab.io/
    targetRevision: 10.2.1
    helm:
      valuesObject:
        upgradeCheck:
          enabled: false
        global:
          revisionHistoryLimit: 0
          appConfig:
            defaultColorMode: 3
            defaultTheme: 2
            defaultSyntaxHighlightingTheme: 5
            object_store:
              enabled: true
              connection:
                secret: object-storage
            terraformState:
              enabled: true
          edition: ee
          hosts:
            domain: nahue.ar
            https: true
          gatewayApi:
            enabled: false
            configureCertmanager: false
            installEnvoy: false
          ingress:
            enabled: true
            configureCertmanager: false
            class: internal-nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-short-lived-prod"
          kas:
            enabled: false
          pages:
            enabled: true
            objectStore:
              connection:
                secret: pages-storage
          redis:
            host: valkey
            auth:
              enabled: true
              secret: valkey-auth
              key: default
          psql:
            database: app
            username: app
            host: postgres-gitlab-rw
            password:
              secret: postgres-gitlab-app
              key: password
        installCertmanager: false
        nginx-ingress:
          enabled: false
        prometheus:
          install: false
        gitlab-runner:
          install: true
          gitlabUrl: "https://gitlab.nahue.ar"
          revisionHistoryLimit: 0
          rbac:
            create: true
          checkInterval: 3
          runners:
            revisionHistoryLimit: 0
            locked: false
            config: |
              [[runners]]
              url = "https://gitlab.nahue.ar"
              clone_url = "https://gitlab.nahue.ar"
                [runners.kubernetes]
                privileged = true
                image = "alpine:latest"
                [runners.cache]
                Type = "s3"
                Path = "runner"
                Shared = true
                  [runners.cache.s3]
                  ServerAddress = "10.10.20.10:30188"
                  BucketName = "runner-cache"
                  BucketLocation = "garage"
                  Insecure = true
                  AuthenticationType = "access-key"
            cache:
              secretName: gitlab-runner-cache-s3
          podAnnotations:
            gitlab.com/prometheus_scrape: "true"
            gitlab.com/prometheus_port: 9252
        gitlab:
          gitlab-shell:
            minReplicas: 1
            maxReplicas: 1
          toolbox:
            backups:
              cron:
                enabled: true
              objectStorage:
                config:
                  secret: backup-storage
            extraEnvFrom:
              COMPRESS_CMD:
                configMapKeyRef:
                  name: gitlab-backup-compression
                  key: COMPRESS_CMD
          gitaly:
            persistence:
              storageClass: "nfs-csi-persistent"
              size: 500Gi
          gitlab-pages:
            ingress:
              tls:
                secretName: pages-tls
          sidekiq:
            minReplicas: 1
            maxReplicas: 1
            extraInitContainers: |
              - name: init-public-key-sidekiq
                image: busybox
                command: ['sh', '-c', 'echo "$PUBLIC_KEY" > /mnt/public.key']
                env:
                  - name: PUBLIC_KEY
                    value: |
                      -----BEGIN PUBLIC KEY-----
                      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAreEfP/ncA1A5cuxBz7rS
                      0Z9DDxdSymLwt2OUSM5WJa+dVB3zSpQjinifdNZq+iHVt8toZBZZ02H3unbn8td0
                      rIifoj4oVpLhvnOAVjUn5tZeUX17tWMA+yyBpf6w6IFxeYBXFd14WOKEarS05U9B
                      59DjBxNqSm+GzhljHO7vvTKy2xXQQ7Fa702DZ7jwr4DJnL87bDXfarnYksuawqtK
                      wQbFHAOvxFj8ghBh1Gshap1abExD4l7QWxFMTCVOkLJmXiqfOi5KuMiaMsSUsCBN
                      QDE3A5aKvpwLGozsvpGRMy5Tt4SgHC7ZbgerBNe75olOoPDxZf7bBt0+O5A/UjK/
                      HwIDAQAB
                      -----END PUBLIC KEY-----
                volumeMounts:
                  - name: public-key
                    mountPath: /mnt
            extraVolumes: |
              - name: public-key
                emptyDir: {}
            extraVolumeMounts: |
              - name: public-key
                mountPath: /srv/gitlab/.license_encryption_key.pub
                subPath: public.key
          webservice:
            minReplicas: 2
            maxReplicas: 5
            extraInitContainers: |
              - name: init-public-key-webservice
                image: busybox
                command: ['sh', '-c', 'echo "$PUBLIC_KEY" > /mnt/public.key']
                env:
                  - name: PUBLIC_KEY
                    value: |
                      -----BEGIN PUBLIC KEY-----
                      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAreEfP/ncA1A5cuxBz7rS
                      0Z9DDxdSymLwt2OUSM5WJa+dVB3zSpQjinifdNZq+iHVt8toZBZZ02H3unbn8td0
                      rIifoj4oVpLhvnOAVjUn5tZeUX17tWMA+yyBpf6w6IFxeYBXFd14WOKEarS05U9B
                      59DjBxNqSm+GzhljHO7vvTKy2xXQQ7Fa702DZ7jwr4DJnL87bDXfarnYksuawqtK
                      wQbFHAOvxFj8ghBh1Gshap1abExD4l7QWxFMTCVOkLJmXiqfOi5KuMiaMsSUsCBN
                      QDE3A5aKvpwLGozsvpGRMy5Tt4SgHC7ZbgerBNe75olOoPDxZf7bBt0+O5A/UjK/
                      HwIDAQAB
                      -----END PUBLIC KEY-----
                volumeMounts:
                  - name: public-key
                    mountPath: /mnt
            extraVolumes: |
              - name: public-key
                emptyDir: {}
            extraVolumeMounts: |
              - name: public-key
                mountPath: /srv/gitlab/.license_encryption_key.pub
                subPath: public.key
            ingress:
              tls:
                secretName: gitlab-tls
        registry:
          hpa:
            minReplicas: 1
            maxReplicas: 1
          storage:
            secret: registry-storage
          ingress:
            tls:
              secretName: registry-tls
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
