apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-gateways
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nginx-fabric
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/shared-gateways/overlays/prod
    repoURL: https://github.com/NPastorale/kubernetes
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
