apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: web
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: ghcr.io/npastorale/charts
    chart: app
    targetRevision: 0.1.0
    helm:
      valuesObject:
        type: Deployment
        image: npastorale/web:0.0.1@sha256:b524ba0c7f7f54fe18c44f26aaf7facc5041e5a9dd8148fee3c9168ebee3b024
        ports:
          http: 8080
        readiness:
          path: /
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            cpu: 100m
            memory: 56Mi
          limits:
            memory: 1Gi
        route:
          gateway: external
          hostnames:
            - nahue.ar
            - www.nahue.ar
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
