apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: syncthing
  labels:
    app: syncthing
spec:
  revisionHistoryLimit: 0
  serviceName: syncthing
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      volumes:
        - name: config
          nfs:
            path: "/mnt/NAS-T/k8s-volumes/persistent/syncthing/config"
            server: 10.10.20.10
        - name: data
          nfs:
            path: "/mnt/NAS-T/k8s-volumes/persistent/syncthing/data"
            server: 10.10.20.10
      containers:
        - name: syncthing
          image: lscr.io/linuxserver/syncthing:v2.1.1-ls220@sha256:b1a5a0ea4b32ecf2672db7c4c56443c5e222cca12d397724ea93c07a6c7564d0
          resources:
            requests:
              memory: "56Mi"
              cpu: "100m"
            limits:
              memory: "8Gi"
              cpu: "4"
          imagePullPolicy: IfNotPresent
          env:
            - name: hostname
              value: syncthing-server
            - name: STNOUPGRADE
              value: "1"
            - name: TZ
              value: "Europe/Madrid"
            - name: PUID
              value: "65534"
            - name: GUID
              value: "65534"
          readinessProbe:
            httpGet:
              path: /rest/noauth/health
              port: 8384
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /rest/noauth/health
              port: 8384
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 12
          ports:
            - containerPort: 8384
            - containerPort: 22000
            - containerPort: 21027
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
