apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: syncthing
  labels:
    app: syncthing
spec:
  revisionHistoryLimit: 0
  serviceName: syncthing
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      volumes:
        - name: config
          nfs:
            path: "/mnt/NAS-T/k8s-volumes/persistent/syncthing/config"
            server: 10.10.20.10
        - name: data
          nfs:
            path: "/mnt/NAS-T/k8s-volumes/persistent/syncthing/data"
            server: 10.10.20.10
      containers:
        - name: syncthing
          image: lscr.io/linuxserver/syncthing:v2.1.2-ls224@sha256:e8cc12a9d538d6896942bb3055be9c5bf1cf44c713dfa617b5d3e72037de00fb
          resources:
            requests:
              memory: "56Mi"
              cpu: "100m"
            limits:
              memory: "8Gi"
              cpu: "4"
          imagePullPolicy: IfNotPresent
          env:
            - name: hostname
              value: syncthing-server
            - name: STNOUPGRADE
              value: "1"
            - name: TZ
              value: "Europe/Madrid"
            - name: PUID
              value: "65534"
            - name: GUID
              value: "65534"
          readinessProbe:
            httpGet:
              path: /rest/noauth/health
              port: 8384
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /rest/noauth/health
              port: 8384
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 12
          ports:
            - containerPort: 8384
            - containerPort: 22000
            - containerPort: 21027
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
