apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddclient
  labels:
    app: ddclient
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ddclient
  template:
    metadata:
      labels:
        app: ddclient
    spec:
      volumes:
        - name: ddclient-conf
          nfs:
            path: "/mnt/NAS-T/k8s-volumes/persistent/ddclient/config"
            server: 10.10.20.10
        - name: ddns-key
          secret:
            secretName: ddclient
            items:
              - key: ddns-key.conf
                path: ddns-key.conf
      containers:
        - name: ddclient
          image: lscr.io/linuxserver/ddclient:v4.0.0-ls233@sha256:61de8a998f00bcf468a361f0df6007fb6ee8b2c6e89ed1c431145a98caeb7755
          resources:
            requests:
              memory: "52Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Madrid"
            - name: DYNU_LOGIN
              valueFrom:
                secretKeyRef:
                  name: ddclient
                  key: dynu-login
            - name: DYNU_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ddclient
                  key: dynu-password
          volumeMounts:
            - name: ddclient-conf
              mountPath: /config/ddclient.conf
              subPath: ddclient.conf
            - name: ddns-key
              mountPath: /etc/ddclient/ddns-key.conf
              subPath: ddns-key.conf
              readOnly: true
