apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ddclient-external
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ddclient
    creationPolicy: Owner
  data:
    - secretKey: dynu-login
      remoteRef:
        key: dynu
        property: login
    - secretKey: dynu-password
      remoteRef:
        key: dynu
        property: password
    - secretKey: ddns-key.conf
      remoteRef:
        key: ddns
        property: conf
