apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ubuntu-prep-https
spec:
  hostnames:
    - ubuntu-prep.nahue.ar
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external
      namespace: nginx-fabric
      sectionName: ubuntu-prep-https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: ubuntu-prep
          port: 443
          weight: 1
