apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  serviceName: home-assistant
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      volumes:
        - name: config
          nfs:
            path: "/mnt/NAS-T/k8s-volumes/persistent/home-assistant/config"
            server: 10.10.20.10
      hostNetwork: true
      containers:
        - name: home-assistant
          image: lscr.io/linuxserver/homeassistant:2026.6.3-ls221@sha256:133f176bb384388701c68ca03d4d6e8816f69d1f56ebbd5a54c23b4014f5c70b
          resources:
            requests:
              memory: "56Mi"
              cpu: "100m"
            limits:
              memory: "8Gi"
              cpu: "4"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Madrid"
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: config
              mountPath: /config
