apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  serviceName: home-assistant
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      volumes:
        - name: config
          nfs:
            path: "/mnt/NAS-T/k8s-volumes/persistent/home-assistant/config"
            server: 10.10.20.10
      hostNetwork: true
      containers:
        - name: home-assistant
          image: lscr.io/linuxserver/homeassistant:2026.4.0-ls199@sha256:d784d0d5f1523e60fcee1621505342f7b98b1c3e2e07e22d1888ff85a961cde3
          resources:
            requests:
              memory: "56Mi"
              cpu: "100m"
            limits:
              memory: "8Gi"
              cpu: "4"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Madrid"
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: config
              mountPath: /config
