apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-secrets
  namespace: hermes
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: hermes-secrets
    creationPolicy: Owner
  data:
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: hermes
        property: telegram_bot_token
    - secretKey: TELEGRAM_ALLOWED_USERS
      remoteRef:
        key: hermes
        property: telegram_allowed_users
    - secretKey: API_SERVER_KEY
      remoteRef:
        key: hermes
        property: api_server_key
    - secretKey: OPENCODE_GO_API_KEY
      remoteRef:
        key: hermes
        property: opencode_go_api_key
    - secretKey: HERMES_DASHBOARD_BASIC_AUTH_PASSWORD
      remoteRef:
        key: hermes
        property: dashboard_basic_auth_password
    - secretKey: HERMES_DASHBOARD_BASIC_AUTH_SECRET
      remoteRef:
        key: hermes
        property: dashboard_basic_auth_secret
    - secretKey: GITLAB_TOKEN
      remoteRef:
        key: hermes
        property: gitlab_token
