apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-config
spec:
  storageClassName: nfs-csi-persistemt
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
