apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hermes
  labels:
    app: hermes
spec:
  serviceName: hermes
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hermes
  template:
    metadata:
      labels:
        app: hermes
    spec:
      containers:
        - name: hermes
          image: nousresearch/hermes-agent:latest
          imagePullPolicy: IfNotPresent
          args:
            - gateway
            - run
          env:
            - name: HERMES_HOME
              value: /opt/data
            - name: HERMES_WRITE_SAFE_ROOT
              value: /opt/data
            - name: API_SERVER_ENABLED
              value: "true"
            - name: API_SERVER_HOST
              value: 0.0.0.0
            - name: API_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: hermes-secrets
                  key: API_SERVER_KEY
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hermes-secrets
                  key: TELEGRAM_BOT_TOKEN
            - name: TELEGRAM_ALLOWED_USERS
              valueFrom:
                secretKeyRef:
                  name: hermes-secrets
                  key: TELEGRAM_ALLOWED_USERS
            - name: OPENCODE_GO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hermes-secrets
                  key: OPENCODE_GO_API_KEY
            - name: HERMES_DASHBOARD
              value: "1"
            - name: HERMES_DASHBOARD_BASIC_AUTH_USERNAME
              value: nahue
            - name: HERMES_DASHBOARD_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hermes-secrets
                  key: HERMES_DASHBOARD_BASIC_AUTH_PASSWORD
            - name: HERMES_DASHBOARD_BASIC_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: hermes-secrets
                  key: HERMES_DASHBOARD_BASIC_AUTH_SECRET
          ports:
            - name: gateway
              containerPort: 8642
            - name: dashboard
              containerPort: 9119
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
            - name: config
              mountPath: /opt/data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: hermes-config
