apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggerbot
  labels:
    app: loggerbot
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: loggerbot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: loggerbot
    spec:
      runtimeClassName: "nvidia"
      containers:
        - name: loggerbot
          image: ttl.sh/loggerbot:24h@sha256:7dd0f4247ed156395031c1ee6ef0868149e8690b8b3aeb74cd533f9b55b5cb45
          resources:
            limits:
              nvidia.com/gpu: 1
          imagePullPolicy: Always
          env:
            - name: TELEGRAM_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-api-key
                  key: telegram-api-key
            - name: MODEL_SIZE
              value: "turbo"
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
