apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegram-api-key-external
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: telegram-api-key
    creationPolicy: Owner
  data:
    - secretKey: telegram-api-key
      remoteRef:
        key: telegram
        property: api-key
